name: build

on:
  push:
    branches: [ master ]
    tags:
      - v*
      - p*
  pull_request:
    branches: [ master ]

  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    name: ${{ matrix.python }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python: [ '3.12' ]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: install requirements
        env:
          MKLROOT: ~/.local
        run: |
          export PYT=$(which python)
          python -m pip install pip build twine --upgrade

      - name: build wheels
        if: startsWith(github.ref, 'refs/tags/')
        env:
          TAG_STRING: ${{ github.event.ref }}
        run: |
          echo ${TAG_STRING:11}
          sed -i "s/version=.*/version='${TAG_STRING:11}',/" setup.py
          python -m pip install wheel
          python -m pip wheel . -w ./dist --no-deps

      - name: release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*

      - name: upload artifacts
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
          retention-days: 2

  pypi:
    name: pypi
    needs: [build]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: build source dist
        env:
          TAG_STRING: ${{ github.event.ref }}
        run: |
          echo ${TAG_STRING:11}
          sed -i "s/version=.*/version='${TAG_STRING:11}',/" setup.py
          python -m pip install pip build twine --upgrade
          python -m build --sdist

      - name: release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*

      - name: build index
        env:
          REPO: ${{ github.repository }}
        run: |
          python .github/workflows/build_pypi.py ${REPO} ./idx-dist/pypi

      - name: setup pages
        uses: actions/configure-pages@v2

      - name: upload artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: './idx-dist'

      - name: deploy to gitHub pages
        id: deployment
        uses: actions/deploy-pages@v4

  publish:
    name: publish
    needs: build
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: build source dist
        env:
          TAG_STRING: ${{ github.event.ref }}
        run: |
          echo ${TAG_STRING:11}
          sed -i "s/version=.*/version='${TAG_STRING:11}',/" setup.py
          python -m pip install pip build twine --upgrade
          python -m build --sdist

      - name: download wheels
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

      - name: publish to pypi
        uses: pypa/gh-action-pypi-publish@v1.4.2
